### ISSUE TITLE
Putting quote in single quotes causes a compilation error

### ISSUE THREAD

**Issue by auraes** [DavidKinder/Inform6#234]
```
[ Main;
   print ''';
];
```
> Inform 6.42 (in development)
> line 3: Error:  Expected ''' but found end of file
> >
> line 3: Error:  Expected comma but found dict word ';
> ];
> '
> >
> line 5: Error:  Expected ']' but found <end of file>
> >
> line 5: Error:  Expected ';' after ']' but found <end of file>
> >
> Compiled with 4 errors (no output)

**Comment by erkyrath** [comment]
Right, quotes inside quotes have to be escaped.

If you want a dictionary word with a single quote in it, write it like this: `'can@{27}t'`.

If you want the ASCII value of a single quote, just write `39` or `$27`.

**Comment by auraes** [comment]
Thank you. This is a recent regression since it worked with the previous 6.42.

**Comment by erkyrath** [comment]
Ok, I didn't realize it was a regression. I didn't make that change on purpose.

I'll try to see what caused it.
